version: 2.1

jobs:
  - build:
      docker:
        - image: vitr/casperjs
      steps:
        - checkout
        - run: 
            name: "Build Example"
            command: |
              echo "this is a build test!"
        - run:
            name: "Another Build Test"
            command: node -v
  - test:
      docker:
        - image: vitr/casperjs
      steps:
        - checkout
        - run: 
            name: "Test Example"
            command: |
              echo "this is a test!"
        - run:
            name: "Another Test"
            command: node -v

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: ci