# version: 2.1

# jobs:
#   - build:
#       docker:
#         - image: vitr/casperjs
#       steps:
#         - checkout
#         - run: 
#             name: "Build Example"
#             command: |
#               echo "this is a build test!"
#         - run:
#             name: "Another Build Test"
#             command: node -v
#   - test:
#       docker:
#         - image: vitr/casperjs
#       steps:
#         - checkout
#         - run: 
#             name: "Test Example"
#             command: |
#               echo "this is a test!"
#         - run:
#             name: "Another Test"
#             command: node -v

# workflows:
#   version: 2.1
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: ci


version: 2
jobs:
  source_checkout:
    docker:
      - image: vitr/casperjs
    working_directory: ~/stratux_ahrs
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/stratux_ahrs
  build:
    docker:
      - image: vitr/casperjs
    working_directory: ~/stratux_ahrs
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Update npm
          command: 'echo "Would update NPM"'
      - run:
          name: Check Phantom JS
          command: 'phantomjs /home/phantomjs/script.js'
      - run:
          name: Check CasperJs
          command: |
            casperjs --version
            # casperjs test mytest.js
            # casperjs test /opt/casperjs/samples/googletesting.js
      - run:
          name: Directory List
          command: |
            ls
            ls ~/stratux_ahrs

workflows:
  version: 2
  build_and_test:
    jobs:
      - source_checkout:
          filters:
            branches:
              only: ci
      - build:
          requires:
            - source_checkout
          filters:
            branches:
              only: ci